name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     - "debug-integration-fail"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
     - "terraform/**"

jobs:
  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@test-int-tests
    with:
      container-name: "admin-ui"
      use-charmcraftcache: true
      node-size: large
